### ISSUE TITLE
Support for Additional Git Servers

### ISSUE THREAD

**Issue by inferno333** [OpenCSGs/csghub-server#103]
The current implementation of CSGHub Server only supports Gitea as the Git server. As mentioned in the roadmap, it would be beneficial to support more mainstream Git repositories in the future. I propose adding support for GitLab and GitHub as additional Git servers.

#### Motivation

This feature would allow users to integrate CSGHub Server with their existing Git workflows, making it more versatile and appealing to a wider range of users.

#### Expected Behavior

The CSGHub Server should be able to connect to and manage repositories on GitLab and GitHub, in addition to Gitea.

#### Acceptance Criteria

* The CSGHub Server can successfully connect to GitLab and GitHub repositories.
* The CSGHub Server can manage repositories on GitLab and GitHub, including creating, updating, and deleting repositories.
* The CSGHub Server can handle authentication and authorization for GitLab and GitHub repositories.

**Comment by Rader** [comment]
Hi @inferno333 ,

Thank you for your feature request! Your suggestion to expand CSGHub's support to include GitLab and GitHub is greatly appreciated. We agree that enhancing integration with these popular platforms would significantly improve versatility and attract a broader user base.

Integrating with additional Git servers aligns well with our roadmap, and your insights on expected behavior and acceptance criteria provide a clear direction for development.

We encourage you to contribute to this feature! If you have experience with GitLab and GitHub APIs, your input on implementation could be invaluable. Feel free to open a discussion on our forum or create a draft pull request if you’d like to collaborate on this. Your contributions can help accelerate the addition of this functionality and ensure it meets our community's needs.

Once again, thank you for your input and enthusiasm for CSGHub! We look forward to possibly collaborating with you on enhancing this project.

Best,

OpenCSG

**Comment by Rader** [comment]
@inferno333  `v0.9.0` has added support for Gitaly (the git server used by Gitlab)
